name: Test and Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: docker build -t react-dice-game ./dice-game
      
      - name: Run Docker Container
        run: docker run -d -p 80:80 --name dice-game-container react-dice-game
      
      - name: Test Application
        run: |
          sleep 10  # Wait for the container to start
          curl -f http://localhost:80 || exit 1

